version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:13.0.1
    container_name: keycloak
    ports: 
      - 8081:8080
      - 8443:8443
    restart: unless-stopped
    environment: 
      # Credentials for admin account
      # -----------------------------
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"

      # Credentials for storing into an external database
      # -------------------------------------------------
      # DB_VENDOR: "postgres | mysql"
      # DB_ADDR: 
      # DB_PORT:
      # DB_DATABASE: 
      # DB_USER:
      # DB_PASSWORD: 
